&INPUT
    project_name = "test-h2o-h2o"

    PAIR_STATE        = BOUND 
    CALCULATION_TYPE  = CORRELATION_SINGLE
    TEMPERATURE       = 300.0
    pair_reduced_mass = 16419.37647762178 ! H2O-H2O, a.m.u.

    so_potential = "build/ai_pes_h2o_h2o_nn.so"
    so_dipole = "build/ai_ids_h2o_h2o.so"
 
    NITERATIONS         = 1 
    TOTAL_TRAJECTORIES  = 4 
    CVODE_TOLERANCE     = 1e-12
    sampling_time       = 200.0
    MaxTrajectoryLength = 100 

    pesmin = -0.007545251105751766 ! = -1656.0 cm-1 

    sampler_Rmin = 5.0
    sampler_Rmax = 10.0
 
    hep_ppf_npoints = 100_000
    hep_ppf_niterations = 5

    hep_m0_npoints = 100_000
    hep_m0_niterations = 5
    
    hep_m2_npoints = 10_000
    hep_m2_niterations = 5 

    cf_filename = "CF-B-H2O-H2O-300.0.txt"
    Rcut = 40.0
    accelerate_averaging = true
&END
 
&MONOMER
    MONOMER_TYPE = ROTOR
    II = { 4065.15542327822, 11618.1179974822, 7552.96257420394 } ! II(H2O), a.u.
&END

&MONOMER
    MONOMER_TYPE = ROTOR
    II = { 4065.15542327822, 11618.1179974822, 7552.96257420394 } ! II(H2O), a.u.
&END
