&INPUT
    PAIR_STATE = FREE_AND_METASTABLE 
    CALCULATION_TYPE = MANUAL 
    TEMPERATURE = 300.0 
    pair_reduced_mass = 3.000920752254033e+04 ! mu(CO-Ar), a.m.u

    so_potential = "build/potv.so"
    
    so_dipole.1 = "build/ind_dipole_coar.so"
    so_dipole.2 = "build/perm_dipole_coar.so"
   
    NITERATIONS = 4 
    TOTAL_TRAJECTORIES = 50 
    CVODE_TOLERANCE = 1e-9
    sampling_time = 200.0
    MaxTrajectoryLength = 65536

    pesmin = -0.0004784152015557534 ! Hartree = -105.0 cm-1
    
    sampler_Rmin = 4.0
    sampler_Rmax = 40.0

    hep_ppf_npoints = 1_000_000
    hep_ppf_niterations = 10

    hep_m0_npoints = 10_000
    hep_m0_niterations = 15
    
    hep_m2_npoints = 10_000
    hep_m2_niterations = 15

    cf_filename = "test.txt"
    Rcut = 40.0
&END

 
&MONOMER
    MONOMER_TYPE = LINEAR_MOLECULE_REQ_INTEGER
    II = {5.7079668371e+04, 5.7079668371e+04, 0.0} ! II(CO), a.u.

    TORQUE_CACHE_LEN = 30
    TORQUE_LIMIT     = 5e-5

    NSWITCH_HISTOGRAM_BINS     = 30 
    NSWITCH_HISTOGRAM_MAX      = 30.0
    NSWITCH_HISTOGRAM_FILENAME = "nswitch.dat"
&END

&MONOMER
    MONOMER_TYPE = ATOM
&END


