&INPUT
   PAIR_STATE        = FREE_AND_METASTABLE
   CALCULATION_TYPE  = PR_MU_TRANSITION_FREQUENCY_SAMPLING
   TEMPERATURE       = 300.0
   pair_reduced_mass = 3.000920752254033e+04 ! mu(CO-Ar), a.m.u

   so_potential = "build/potv.so"
   so_dipole = "build/perm_dipole_coar.so"

   NITERATIONS         = 10
   TOTAL_TRAJECTORIES  = 200
   CVODE_TOLERANCE     = 1e-8
   sampling_time       = 200.0
   MaxTrajectoryLength = 65536

   pesmin = -0.0004784152015557534 ! Hartree = -105.0 cm-1

   sampler_Rmin      = 4.0
   sampler_Rmax      = 40.0
   initialM0_npoints = 10000
   initialM2_npoints = 10000

   R0 = 40.0
   sf_filename = "SF-PRMU-TFS-CO-Ar-300.0.txt"
   ApproximateFrequencyMax = 150.0
 
   average_time_between_collisions_per_j = {
      2.596000e+06, ! kappa=1, a.t.u.
      2.855600e+06, ! kappa=2, a.t.u.
      3.141160e+06, ! kappa=3, a.t.u.
      3.455276e+06, ! kappa=4, a.t.u.
      3.800804e+06, ! kappa=5, a.t.u.
      4.180884e+06, ! kappa=6, a.t.u.
      4.598972e+06, ! kappa=7, a.t.u.
      5.058870e+06, ! kappa=8, a.t.u.
      5.564757e+06, ! kappa=9, a.t.u.
      6.121232e+06, ! kappa=10, a.t.u.
      6.733356e+06, ! kappa=11, a.t.u.
      7.406691e+06, ! kappa=12, a.t.u.
      8.147360e+06, ! kappa=13, a.t.u.
      8.962096e+06, ! kappa=14, a.t.u.
      9.858306e+06, ! kappa=15, a.t.u.
      1.084414e+07, ! kappa=16, a.t.u.
      1.192855e+07, ! kappa=17, a.t.u.
      1.312140e+07, ! kappa=18, a.t.u.
      1.443354e+07, ! kappa=19, a.t.u.
      1.587690e+07, ! kappa=20, a.t.u.
      1.746459e+07, ! kappa=21, a.t.u.
      1.921105e+07, ! kappa=22, a.t.u.
      2.113215e+07, ! kappa=23, a.t.u.
      2.324537e+07, ! kappa=24, a.t.u.
      2.556990e+07, ! kappa=25, a.t.u.
      2.812689e+07, ! kappa=26, a.t.u.
      3.093958e+07, ! kappa=27, a.t.u.
      3.403354e+07, ! kappa=28, a.t.u.
      3.743689e+07, ! kappa=29, a.t.u.
      4.118058e+07  ! kappa=30, a.t.u.
   }
&END

&MONOMER
    MONOMER_TYPE = LINEAR_MOLECULE_REQ_INTEGER
    II           = {5.7079668371e+04, 5.7079668371e+04, 0.0} ! II(CO), a.u.

    TORQUE_CACHE_LEN = 3 
    TORQUE_LIMIT     = 5e-7
&END

&MONOMER
    MONOMER_TYPE = ATOM
&END
