&INPUT
   PAIR_STATE        = FREE_AND_METASTABLE
   CALCULATION_TYPE  = PR_MU_TRANSITION_FREQUENCY_SAMPLING
   TEMPERATURE       = 300.0
   pair_reduced_mass = 3.000920752254033e+04 ! mu(CO-Ar), a.m.u

   so_potential = "build/potv.so"
   so_dipole = "build/perm_dipole_coar.so"

   NITERATIONS         = 10
   TOTAL_TRAJECTORIES  = 200
   CVODE_TOLERANCE     = 1e-8
   sampling_time       = 200.0
   MaxTrajectoryLength = 65536

   pesmin = -0.0004784152015557534 ! Hartree = -105.0 cm-1

   sampler_Rmin      = 4.0
   sampler_Rmax      = 40.0
   initialM0_npoints = 10000
   initialM2_npoints = 10000

   R0 = 100.0
   sf_filename = "SF-PRMU-DQS-CO-Ar-300.0.txt"
   ApproximateFrequencyMax = 150.0
&END

&MONOMER
    MONOMER_TYPE = LINEAR_MOLECULE_REQ_INTEGER
    II           = {5.7079668371e+04, 5.7079668371e+04, 0.0} ! II(CO), a.u.

    TORQUE_CACHE_LEN = 2
    TORQUE_LIMIT     = 5e-7
&END

&MONOMER
    MONOMER_TYPE = ATOM
&END
