&INPUT
    CALCULATION_TYPE = PROCESSING
&END

&PROCESSING
    READ_SPECTRUM("MT_CH4_CO2/Turbet2020/Turbet2020-200.0K.txt")
      
    INV_D3()
    DUP()
      COMPUTE_Mn_CLASSICAL_DETAILED_BALANCE(n = 0)
      WRITE_FLOAT("Turbet2020-moments.txt", "a", "200.0 %.6e ")
      
      COMPUTE_Mn_CLASSICAL_DETAILED_BALANCE(n = 2)
      WRITE_FLOAT("Turbet2020-moments.txt", "a", "%.6e")
&END
