name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Doxygen
        run: |
          sudo apt-get update
          DOXYGEN_VERSION="1.14.0"
          wget https://www.doxygen.nl/files/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz

          mkdir -p $HOME/doxygen
          ln -sf $(pwd)/doxygen-${DOXYGEN_VERSION}/bin/doxygen $HOME/doxygen/doxygen
          export PATH="$(HOME)/doxygen:$PATH"

          rm doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          
          doxygen --version
      - name: Create docs directory
        run: mkdir -p ./docs/html

      - name: Generate Documentation
        run: doxygen Doxyfile

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './doxydocs/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
