name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches: [ main ]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository 
        uses: actions/checkout@v4

      - name: Install LaTeX
        uses: zauguin/install-texlive@v4
        with:
          packages: >
            latex latex-bin latex-bin-dev

      - run: 
          pdflatex --version

      - name: Install and Run Doxygen
        run: |
          sudo apt-get update
          sudo apt-get install -y graphviz

          DOXYGEN_VERSION="1.14.0"
          wget https://www.doxygen.nl/files/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          tar -xvf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz

          mkdir -pv $HOME/doxygen
          ln -sf $(pwd)/doxygen-${DOXYGEN_VERSION}/bin/doxygen $HOME/doxygen/doxygen
          export PATH="${HOME}/doxygen:$PATH"

          rm doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          
          doxygen --version
        
          mkdir -p ./docs/html
          doxygen Doxyfile

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './doxydocs/html'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
